import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "GRAPHICS CAMO BASKETBALL JERSEY",
    product: "cloth",
    category: "Men",
    originalPrice: 2999,
    discountedPrice: 1999,
    description:
      "A BASKETBALL JERSEY WITH CAMO-PRINT DETAILS MADE WITH RECYCLED MATERIALS",
    rating: 4.5,
    avalabelSize: ["XS", "S", "M", "l", "XL"],
    isBestseller: false,
    isTrending: false,
    imageSource: "https://i.ibb.co/bvHM3vM/GRAPHICS-CAMO-BASKETBALL-JERSEY.jpg",
    quantity: 15,
    inStock: true,
    isNewArrival: true,
  },
  {
    _id: uuid(),
    name: "AEROREADY FULL ZIP HOODIE",
    product: "cloth",
    category: "Women",
    originalPrice: 2499,
    discountedPrice: 1999,
    description: "AN EVERYDAY TEE WITH GLAMMED-UP 3-STRIPES.",
    rating: 4,
    avalabelSize: ["XS", "S", "M", "l", "XL"],
    isBestseller: false,
    imageSource: "https://i.ibb.co/8s80vLn/AEROREADY-FULL-ZIP-HOODIE.jpg",
    quantity: 12,
    inStock: true,
    isNewArrival: false,
  },
  {
    _id: uuid(),
    name: "ADIDAS SPRT TRACK JACKET",
    product: "cloth",
    category: "Men",
    originalPrice: 7999,
    discountedPrice: 5599,
    description:
      "A TRACK JACKET WITH AN ARCHIVE-INSPIRED DESIGN THAT'S JUST AS FRESH TODAY.",
    rating: 2,
    avalabelSize: ["XS", "S", "M", "l", "XL"],
    isBestseller: true,
    isTrending: false,
    imageSource:
      "https://i.ibb.co/qxh100V/ADIDAS-SPRT-SHARK-WOVEN-TRACK-JACKET.jpg",
    quantity: 7,
    inStock: true,
    isNewArrival: false,
  },
  {
    _id: uuid(),
    name: "ADILETTE BONEGA ",
    product: "shoe",
    category: "Women",
    originalPrice: 4999,
    discountedPrice: 3499,
    description: "CASUAL ADILETTE  WITH A CHIC DESIGN.",
    rating: 3.5,
    avalabelSize: ["5", "6", "7", "8", "9", "10"],
    isBestseller: false,
    isTrending: false,
    imageSource: "https://i.ibb.co/TgFPn7w/ADILETTE-BONEGA.jpg",
    quantity: 15,
    inStock: true,
    isNewArrival: true,
  },
  {
    _id: uuid(),
    name: "NMD_R1 PRIMEBLUE SHOES",
    product: "shoe",
    category: "Men",
    originalPrice: 12999,
    discountedPrice: 11999,
    description: "RUNNING SHOES FOR SPEED AND STABILITY.",
    rating: 3,
    avalabelSize: ["5", "6", "7", "8", "9", "10"],
    isBestseller: true,
    imageSource: "https://i.ibb.co/SyvmCTT/NMD-R1-PRIMEBLUE-SHOES.jpg",
    quantity: 5,
    inStock: true,
    isNewArrival: false,
  },
  {
    _id: uuid(),
    name: "ADIDAS ZX 8000 X LEGO® SHOES",
    product: "shoe",
    category: "Kids",
    originalPrice: 7599,
    discountedPrice: 2999,
    description:
      "BRING A SENSE OF PLAY TO YOUR DAY WITH THE ADIDAS ZX 8000 X LEGO® SHOES.",
    rating: 5,
    avalabelSize: ["3", "4", "5", "6"],
    isBestseller: false,
    imageSource: "https://i.ibb.co/Pw7gfRK/ADIDAS-ZX-8000-X-LEGO-SHOES.jpg",
    quantity: 10,
    inStock: true,
    isNewArrival: false,
  },
  {
    _id: uuid(),
    name: "ZX 1K BOOST SHOES",
    product: "shoe",
    category: "Women",
    originalPrice: 7999,
    discountedPrice: 4999,
    description: "MATERIAL-MIX SHOES FOR NON-STOP COMFORT.",
    rating: 2,
    avalabelSize: ["4", "5", "6", "7", "8", "9", "10"],
    isBestseller: true,
    isTrending: false,
    imageSource: "https://i.ibb.co/vZT2j8w/ZX-1-K-BOOST-SHOES.jpg",
    quantity: 8,
    inStock: true,
    isNewArrival: false,
  },

  {
    _id: uuid(),
    name: "ADIDAS X CHELSA TEE",
    product: "cloth",
    category: "Kids",
    originalPrice: 1400,
    discountedPrice: 600,
    description: "AN EVERYDAY TEE WITH GLAMMED-UP MARVEL SPIDER-MAN",
    rating: 3.5,
    avalabelSize: ["XS", "S", "M", "l", "XL"],
    isBestseller: false,
    isTrending: false,
    imageSource: "https://i.ibb.co/WBxsFZs/ADIDAS-X-CHELSA-TEE.jpg",
    quantity: 12,
    inStock: true,
    isNewArrival: true,
  },
  {
    _id: uuid(),
    name: "GRAND COURT SHOES",
    product: "shoe",
    category: "Kids",
    originalPrice: 3599,
    discountedPrice: 2999,
    description: "LOW-PROFILE SHOES INSPIRED BY RETRO SPORT STYLES",
    rating: 2,
    avalabelSize: ["3", "4", "5", "6"],
    isBestseller: false,
    imageSource: "https://i.ibb.co/tYctxCX/GRAND-COURT-SHOES.jpg",
    quantity: 3,
    inStock: true,
    isNewArrival: false,
  },
];
